// Re-export types from types file for backwards compatibility
export type { Product, Category, MetalFinish, CartItem, Order } from "./products-types";
export { getAllCategories, getAllMetalFinishes } from "./products-types";

// Import types for use in this file
import type { Product, Category } from "./products-types";

// Static product data - MVP (fallback/default products)
export const products: Product[] = [
  {
    sku: "VA-RING-001",
    product_id: "va-01",
    title: "Solitaire Glow Ring",
    category: "rings",
    price: 899,
    cost_price: 450,
    stock_qty: 25,
    weight: 3.5,
    metal_finish: "gold",
    images: ["/images/ring-1.jpg"],
    description: "Anti-tarnish gold plated ring with polished finish. Hypoallergenic. Care: avoid perfumes; clean with soft cloth.",
    short_description: "Anti-tarnish plated ring with polished finish.",
    tags: ["ring", "gold", "everyday", "minimal"],
    dimensions: { length: 2, width: 2, height: 0.5 },
    shipping_class: "standard",
    slug: "solitaire-glow-ring",
    is_new: true,
    size_options: ["6", "7", "8", "9"],
  },
  {
    sku: "VA-EAR-001",
    product_id: "va-02",
    title: "Petal Drop Earrings",
    category: "earrings",
    price: 699,
    cost_price: 350,
    stock_qty: 18,
    weight: 2.2,
    metal_finish: "gold",
    images: ["/images/earrings-1.jpg"],
    description: "Lightweight everyday earrings with subtle shimmer. Anti-tarnish gold plating ensures long-lasting beauty. Perfect for daily wear.",
    short_description: "Lightweight everyday earrings with subtle shimmer.",
    tags: ["earrings", "gold", "drop", "everyday"],
    dimensions: { length: 3, width: 1.5, height: 0.3 },
    shipping_class: "standard",
    slug: "petal-drop-earrings",
    is_new: true,
  },
  {
    sku: "VA-PEND-001",
    product_id: "va-03",
    title: "Minimal Pendant",
    category: "pendants",
    price: 649,
    cost_price: 325,
    stock_qty: 22,
    weight: 4.1,
    metal_finish: "gold",
    images: ["/images/pendant-1.jpg"],
    description: "Elegant pendant on adjustable chain. Anti-tarnish plating. Hypoallergenic. Adjustable length chain (16-18 inches).",
    short_description: "Elegant pendant on adjustable chain.",
    tags: ["pendant", "gold", "minimal", "chain"],
    dimensions: { length: 2.5, width: 1.8, height: 0.4 },
    shipping_class: "standard",
    slug: "minimal-pendant",
  },
  {
    sku: "VA-BRAC-001",
    product_id: "va-04",
    title: "Daily Wear Bracelet",
    category: "bracelets",
    price: 499,
    cost_price: 250,
    stock_qty: 30,
    weight: 8.5,
    metal_finish: "gold",
    images: ["/images/bracelet-1.jpg"],
    description: "Comfort fit, anti-tarnish plating. Hypoallergenic. Adjustable sizing. Perfect for everyday elegance.",
    short_description: "Comfort fit, anti-tarnish plating.",
    tags: ["bracelet", "gold", "everyday", "comfort"],
    dimensions: { length: 18, width: 0.8, height: 0.6 },
    shipping_class: "standard",
    slug: "daily-wear-bracelet",
  },
  // Additional products for better collection
  {
    sku: "VA-RING-002",
    product_id: "va-05",
    title: "Elegant Band Ring",
    category: "rings",
    price: 749,
    cost_price: 375,
    stock_qty: 20,
    weight: 2.8,
    metal_finish: "rose-gold",
    images: ["/images/ring-1.jpg"],
    description: "Minimalist band ring in rose gold finish. Anti-tarnish and hypoallergenic. Timeless design.",
    short_description: "Minimalist band ring in rose gold finish.",
    tags: ["ring", "rose-gold", "band", "minimal"],
    dimensions: { length: 2, width: 0.5, height: 0.3 },
    shipping_class: "standard",
    slug: "elegant-band-ring",
    size_options: ["6", "7", "8", "9"],
  },
  {
    sku: "VA-EAR-002",
    product_id: "va-06",
    title: "Classic Stud Earrings",
    category: "earrings",
    price: 549,
    cost_price: 275,
    stock_qty: 35,
    weight: 1.5,
    metal_finish: "silver",
    images: ["/images/earrings-1.jpg"],
    description: "Versatile stud earrings in silver finish. Perfect for every occasion. Anti-tarnish plating.",
    short_description: "Versatile stud earrings in silver finish.",
    tags: ["earrings", "silver", "stud", "classic"],
    dimensions: { length: 0.8, width: 0.8, height: 0.5 },
    shipping_class: "standard",
    slug: "classic-stud-earrings",
  },
  {
    sku: "VA-PEND-002",
    product_id: "va-07",
    title: "Lotus Pendant",
    category: "pendants",
    price: 799,
    cost_price: 400,
    stock_qty: 15,
    weight: 5.2,
    metal_finish: "gold",
    images: ["/images/pendant-1.jpg"],
    description: "Inspired by the lotus, this pendant symbolizes purity and elegance. Anti-tarnish gold plating.",
    short_description: "Lotus-inspired pendant with elegant design.",
    tags: ["pendant", "gold", "lotus", "elegant"],
    dimensions: { length: 3, width: 2.5, height: 0.5 },
    shipping_class: "standard",
    slug: "lotus-pendant",
  },
  {
    sku: "VA-BRAC-002",
    product_id: "va-08",
    title: "Delicate Chain Bracelet",
    category: "bracelets",
    price: 599,
    cost_price: 300,
    stock_qty: 25,
    weight: 6.8,
    metal_finish: "silver",
    images: ["/images/bracelet-1.jpg"],
    description: "Delicate chain bracelet with subtle charm. Adjustable length. Anti-tarnish silver finish.",
    short_description: "Delicate chain bracelet with subtle charm.",
    tags: ["bracelet", "silver", "chain", "delicate"],
    dimensions: { length: 19, width: 0.5, height: 0.4 },
    shipping_class: "standard",
    slug: "delicate-chain-bracelet",
  },
];

